"""PostgreSQL backend (asyncpg).

asyncpg uses positional ``$1, $2, …`` parameters natively. SQL generated by
the agent uses ``?`` and is transpiled through sqlglot before execution;
internal queries here write the ``$n`` form directly.
"""

from __future__ import annotations

import re
from collections.abc import Mapping, Sequence
from typing import Any

import asyncpg

from qbagent.db.backend import Backend, SchemaDialect

_QMARK = re.compile(r"\?")


def _qmark_to_numbered(sql: str) -> str:
    """Rewrite ``?`` placeholders to ``$1, $2, …`` for asyncpg.

    Simple replace — any ``?`` characters embedded in string literals are
    callers' responsibility; qbagent never emits those.
    """
    counter = [0]

    def repl(_: re.Match[str]) -> str:
        counter[0] += 1
        return f"${counter[0]}"

    return _QMARK.sub(repl, sql)


class PostgresBackend(Backend):
    dialect: SchemaDialect = "postgres"

    def __init__(self, db_url: str) -> None:
        self._dsn = db_url
        self._pool: asyncpg.Pool | None = None

    async def connect(self) -> None:
        if self._pool is not None:
            return
        self._pool = await asyncpg.create_pool(dsn=self._dsn, min_size=1, max_size=5)

    async def close(self) -> None:
        if self._pool is None:
            return
        pool, self._pool = self._pool, None
        await pool.close()

    async def initialize_schema(self) -> None:
        pool = self._require_pool()
        async with pool.acquire() as conn, conn.transaction():
            for stmt in self._load_ddl_statements():
                await conn.execute(stmt)

    async def execute_read(
        self,
        sql: str,
        params: Sequence[Any] | Mapping[str, Any] | None = None,
    ) -> list[dict[str, Any]]:
        pool = self._require_pool()
        sql, args = _coerce_params(sql, params)
        async with pool.acquire() as conn:
            records = await conn.fetch(sql, *args)
            return [dict(r) for r in records]

    async def execute_write(
        self,
        sql: str,
        params: Sequence[Any] | Mapping[str, Any] | None = None,
    ) -> int:
        pool = self._require_pool()
        sql, args = _coerce_params(sql, params)
        async with pool.acquire() as conn:
            status = await conn.execute(sql, *args)
            return _rowcount_from_status(status)

    async def bulk_upsert(
        self,
        table: str,
        rows: Sequence[Mapping[str, Any]],
        pk_column: str,
    ) -> int:
        if not rows:
            return 0
        columns = list(rows[0].keys())
        placeholders = ", ".join(f"${i + 1}" for i in range(len(columns)))
        col_list = ", ".join(columns)
        update_cols = [c for c in columns if c != pk_column]
        if update_cols:
            update_clause = ", ".join(f"{c} = EXCLUDED.{c}" for c in update_cols)
            sql = (
                f"INSERT INTO {table} ({col_list}) VALUES ({placeholders}) "
                f"ON CONFLICT ({pk_column}) DO UPDATE SET {update_clause}"
            )
        else:
            sql = (
                f"INSERT INTO {table} ({col_list}) VALUES ({placeholders}) "
                f"ON CONFLICT ({pk_column}) DO NOTHING"
            )
        values_list = [tuple(row.get(c) for c in columns) for row in rows]

        pool = self._require_pool()
        async with pool.acquire() as conn, conn.transaction():
            await conn.executemany(sql, values_list)
            return len(values_list)

    def _require_pool(self) -> asyncpg.Pool:
        if self._pool is None:
            raise RuntimeError("PostgresBackend.connect() must be called before use.")
        return self._pool


def _coerce_params(
    sql: str,
    params: Sequence[Any] | Mapping[str, Any] | None,
) -> tuple[str, tuple[Any, ...]]:
    """Normalize ``?``-style params to asyncpg's ``$n`` form."""
    if params is None:
        return sql, ()
    if isinstance(params, Mapping):
        raise TypeError(
            "PostgresBackend does not support named parameters; pass a sequence of values."
        )
    return _qmark_to_numbered(sql), tuple(params)


def _rowcount_from_status(status: str) -> int:
    """Parse an asyncpg command tag like ``'UPDATE 3'`` into a row count."""
    parts = status.rsplit(" ", 1)
    try:
        return int(parts[-1])
    except ValueError:
        return 0
